### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by tomnatt**

### CODE REVIEW

**Comment by tomnatt** [comment]
Moving heroku deployment back to `master`

**Comment by bathwebservices** [comment]
__________________________________
Type your response ABOVE THIS LINE to reply

------------------------------------------------------------------------------------------------------------

Thank you for your query. This is an automatic response to let you know this has been received and we will respond to you as soon as we can.

If you need to provide additional information then please reply to this message.

You can also find answers to common queries at http://go.bath.ac.uk/dsc

Regards,

Digital Marketing and Communications
web-support@bath.ac.uk

Thanks in advance for your patience and support.

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #1271.
------------------------------------------------------------------------------------------------------------


[[4faf74e7688010b6d0bdb9e0f2c2b91d86b712ff-639639307]]

**Comment by bathwebservices** [comment]
__________________________________
Type your response ABOVE THIS LINE to reply

------------------------------------------------------------------------------------------------------------

Thank you for your query. This is an automatic response to let you know this has been received and we will respond to you as soon as we can.

If you need to provide additional information then please reply to this message.

You can also find answers to common queries at http://go.bath.ac.uk/dsc

Regards,

Digital Marketing and Communications
web-support@bath.ac.uk

Thanks in advance for your patience and support.

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #1273.
------------------------------------------------------------------------------------------------------------


[[754441f6343dcf3239c952092f0b68dacd81be6c-639639499]]

**Comment by bathwebservices** [comment]
__________________________________
Type your response ABOVE THIS LINE to reply

------------------------------------------------------------------------------------------------------------

Thank you for your query. This is an automatic response to let you know this has been received and we will respond to you as soon as we can.

If you need to provide additional information then please reply to this message.

You can also find answers to common queries at http://go.bath.ac.uk/dsc

Regards,

Digital Marketing and Communications
web-support@bath.ac.uk

Thanks in advance for your patience and support.

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #1272.
------------------------------------------------------------------------------------------------------------


[[0dcebb3d15660e52225b3670a4bab7a21f88d377-639639410]]

**Pull request merged**
